// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace SimpleSocialNetwork.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedParentIdForFeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedParentIdForFeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201806291623490_AddedParentIdForFeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
